### PR TITLE
new poke images

### PR DESCRIPTION
**Pull request by MrYadro**
I don't think you need icons that big because they sometimes cover each other. Also there are gym and pokestop images in case you will add that functionality.

Just in case pokemon images I got from pokiego.com, and others made by me.

### CODE REVIEW

**Comment by MrYadro** [comment]
I'm not complaining about not merging that as it's up to you, but since you merged other commit with 32x32 icons, I think you should resize pokemon icons to 32x32. IMO smaller = better, even of FullHD display I could easily press those icons, for those who can't you have icon scaling.

**Comment by BrianEstrada** [comment]
Sorry Ill take a look at the icons when I get home reopen it

**Comment by MrYadro** [comment]
What's the verdict on this pull after all? I'm not forcing you just in case you forgot to check it.

**Comment by BrianEstrada** [comment]
you never resubmitted :P

**Pull request closed without merging**
