### PR TITLE
New poke icons

### PR DESCRIPTION
**Pull request by MrYadro**
I don't think you need icons that big because they sometimes cover each other. Also there are gym and pokestop images in case you will add that functionality.

All icons are 32x32

Just in case pokemon images I got from pokiego.com, and others (which were merged before) made by me.

### CODE REVIEW

**Comment by BrianEstrada** [comment]
I'm at work right now I'll check out the icons when I get home.

**Comment by guidodavide** [comment]
IMHO
Well, why don't you use the old ones (bigger) inside the little dialog that pops up whenever an user clicks on the detected (available on map) pokemon?
Maybe it's preferrable!

**Comment by BrianEstrada** [comment]
I've tried adding these to the app but the issue is that 32x32 is too small for me to draw timers ontop of...I'm trying to find a work around but so far I can't find a way to expand the canvas because of the size of the icons :( (If you want to see what I mean go to the APP and set icon size to small and you'll see what I mean)

**Comment by alvarodevlabs** [comment]
I think a good idea to dont lag the App is show the countdown of every pokemon when you click on it, i mesn, display the countdown on the dialog of every pokemon you click

**Pull request closed without merging**
