### PR TITLE
Material Design redesign

### PR DESCRIPTION
**Pull request by tajchert**
"Small" Material Design redesign of MapsActivity with usage of[ Google icons ](https://design.google.com/icons/) and FAB as main action.

Removed bottom layout with ugly menu/options button - was moved to Toolbar Menu with overflow icon changed to "setting gear" with black not gray to make it better stand out over MapView itself.
Due to it moved MyLocation button a bit lower (setPadding - 48dp from top to make sure no MapView buttons wouldn't be covered in future by Toolbar.

Instead of "classic" buttons added FAB with circle-shaped ProgressBar around it. Icon of FAB changes from "scan" to "pause".

Removed custom MenuItem object, and as well Lombok library as it was used only there.

Only thing I'm not perfectly happy with is "My Location" button on MapView - which I would move to left-top corner but it requires own implementation of that button (or overkill with setPadding()).

Old design:
Old design
New design (open settings):
screenshot_20160724-031111
New design (closesettings):
screenshot_20160724-031106

### CODE REVIEW

**Comment by BrianEstrada** [comment]
Damn this looks nice thanks! merging.

**Comment by metherul** [comment]
Wouldn't it make sense for the FAB to go from "start" to "stop" instead of "pause"?

Semantics aside, this looks fantastic.

**Comment by tajchert** [comment]
Totally forgot to upload screenshot with not started scan (take a look below).

screenshot_20160724-032804

About Play/Pause - it was my personal taste as pause to me looks more intuitive and clear. Also when you suddenly see white rectangle instead of an icon you might thing something went wrong with loading icon (I know this is an edge case but still might happen).

**Comment by tajchert** [comment]
Probably best of the best would be XML animation of scanning (same as when not scanning - but rotating) when running a scan. But I'm not a designer - that would be good to add in issues if @BrianEstrada you see it would make a nice feature.

**Comment by metherul** [comment]
Ahh, that makes sense. 

For the location marker, shouldn't it be disabled by:
`UiSettings.setMyLocationButtonEnabled(false)`

so that you can replace it with your own button which calls:
`onMyLocationButtonClick ()`

https://developers.google.com/maps/documentation/android-api/location#my-location

If I have anything wrong, make sure to tell me!

**Comment by tajchert** [comment]
@metherul 
Yes, hiding default one is easy.
But adding new one and making it work is more tricky - you need to know where is user current location (own location listener) as map method mMap.getLocation() is deprecated. 

About you advice - onMyLocationButtonClick is a listener - so you can add listener when user presses default map myLocationButton (which we try to hide/replace by our own) not a method to call by custom myLocationButton to make it act as default one (which would be nice).

**Comment by metherul** [comment]
What about using `Location getLastLocation (GoogleApiClient client)` to find the "current" location of the user? Then you can center the camera on said location using something like this:  

```
LatLng coordinate = new LatLng(lat, lng);
CameraUpdate yourLocation = CameraUpdateFactory.newLatLngZoom(coordinate, 5);
map.animateCamera(yourLocation);
```

which "should" animate the camera into the last known location of the user. 

As always, I might know what I'm doing but I might not. If I get anything wrong, make sure to tell me.

**Pull request merged**
