### PR TITLE
Shuffle icons, Lured Pokestop icons, etc.

### PR DESCRIPTION
**Pull request by Chupalika**
I had been experimenting and tweaking, and thought maybe you might like the changes. (Sorry if there are lots of problems, I'm pretty new to github and android developing)
- Can toggle whether to show Pokemon Shuffle icons instead of the old sprites (I think they are easier to distinguish!)
- Replaced the Gym icons and Pokestop icons
- Can toggle whether to show the Pokemon icon that is currently at a Lured Pokestop instead of the Lured Pokestop icon (Filtered Pokemon will still show a Lured Pokestop icon)
- Filtered Pokemon will show up at the top of the Filtered list
- Pokestops and Gyms don't have their text above them (it was too cluttered in my opinion) (Lured Pokestops still have their timer)
- Some other minor stuff I forget

### CODE REVIEW

**Comment by markhaehnel** [comment]
I don't think thats what we want. But @BrianEstrada and @rhari991 should share their opinion on this too.

**Comment by rhari991** [comment]
Some of these are good ideas, but I dont think we want all the changes in together.
Please make separate pull requests if you are working on different features.

**Comment by markhaehnel** [comment]
@Chupalika It's good to do small changes and create a pull request more often. It's easier for us to check the stuff and we can easily approve or decline single features.

**Comment by Chupalika** [comment]
ohh I see, thanks! I'm not home right now, so maybe later tonight

**Comment by BrianEstrada** [comment]
yeah definately put in seperate pull request because I'd like to add some of these! thanks @Chupalika

**Pull request closed without merging**
