### PR TITLE
Blacklist Toggle

### PR DESCRIPTION
**Pull request by j0be**
Committing blacklist toggle, although for some reason I can't get the icons to show up.

### CODE REVIEW

**Comment by j0be** [comment]
I just thought of this. I probably sized my icons wrong, which is why the on state is entirely white, and the off state doesn't show up.

**Comment by yulkoz** [comment]
Cant detect anything now....  :(

**Comment by kurasa** [comment]
yes.. Cant detect anything now.... :(

**Comment by j0be** [comment]
Oh lord people. This wasn't merged in yet as well as it had nothing to do with the pokemon dissappearing.

See this post for more information. https://www.reddit.com/r/PokeScanner/comments/4w143n/announcement_niantec_has_completely_changed_the/

**Pull request closed without merging**
