### PR TITLE
Preventing driving mode from changing zoom level

### PR DESCRIPTION
**Pull request by j0be**
his prevents driving mode from hijacking the zoom when it is re-centering the map.

### CODE REVIEW

**Comment by j0be** [comment]
Map refresh rate may halt the zoom in on initial load in this, but it will now allow users to control the zoom level while in driving mode.

**Comment by j0be** [comment]
So, @BrianEstrada, did this work properly? The only time zoom got halted for my testing was during the initial zoom in from the world map and driving mode is enabled. 

I haven't been able to mess with the POKEMONGO.jar, so I wasn't able to make CameraPosition a method available to the java files. (https://developers.google.com/android/reference/com/google/android/gms/maps/model/CameraPosition)

If that was available, then I could check if zoom > 15 and zoom anyway on drive mode.

**Comment by BrianEstrada** [comment]
@j0be We've completly changed driving mode it's going to be a seperate mode from the window so check out the latest build and you can see where we're at with that I think for driving mode we're going to stick with enforcing a zoom level (15-20)

**Comment by j0be** [comment]
I just built the app. I'll check it out now. I haven't been able to touch non-work code at all today. I'll let you know what I think

**Pull request merged**
